{% set version = "0.9.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-geometa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geometa_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geometa/geometa_{{ version }}.tar.gz
  sha256: 8bdca4ff5fb874d98773be7c479b79c063364de6b020964e976a9803812041b3

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-xml
    - r-httr
    - r-jsonlite
    - r-keyring
    - r-readr
  run:
    - r-base
    - r-r6
    - r-xml
    - r-httr
    - r-jsonlite
    - r-keyring
    - r-readr

test:
  commands:
    - $R -e "library('geometa')"           # [not win]
    - "\"%R%\" -e \"library('geometa')\""  # [win]

about:
  home: https://github.com/eblondel/geometa/wiki
  license: MIT
  summary: Provides facilities to handle reading and writing of geographic metadata defined with OGC/ISO 19115, 11119 and 19110 geographic information metadata standards, and encoded using the ISO 19139 (XML) standard. It includes also a facility to check the validity of ISO 19139 XML encoded metadata.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - marie59

# Package: geometa
# Type: Package
# Title: Tools for Reading and Writing ISO/OGC Geographic Metadata
# Version: 0.6-6
# Date: 2022-01-25
# Authors@R: c(person("Emmanuel", "Blondel", role = c("aut", "cre"), email = "emmanuel.blondel1@gmail.com", comment = c(ORCID = "0000-0002-5870-5762")))
# Maintainer: Emmanuel Blondel <emmanuel.blondel1@gmail.com>
# Description: Provides facilities to handle reading and writing of geographic metadata defined with OGC/ISO 19115, 11119 and 19110 geographic information metadata standards, and encoded using the ISO 19139 (XML) standard. It includes also a facility to check the validity of ISO 19139 XML encoded metadata.
# Depends: R (>= 3.3.0)
# Imports: methods, R6, XML, httr, jsonlite, keyring
# Suggests: sf, ncdf4, EML, emld, units, testthat, roxygen2
# License: MIT + file LICENSE
# URL: https://github.com/eblondel/geometa/wiki
# BugReports: https://github.com/eblondel/geometa/issues
# LazyLoad: yes
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Packaged: 2022-01-25 13:58:52 UTC; manub
# Author: Emmanuel Blondel [aut, cre] (<https://orcid.org/0000-0002-5870-5762>)
# Repository: CRAN
# Date/Publication: 2022-01-26 20:40:02 UTC
